package attendance.entity;
// Generated May 3, 2016 10:26:54 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Attendance generated by hbm2java
 */
public class Attendance  implements java.io.Serializable {


     private Integer id;
     private Course course;
     private Student student;
     private boolean isPresent;
     private Date date;
     private String comments;

    public Attendance() {
    }

    public Attendance(Course course, Student student, boolean isPresent, Date date, String comments) {
       this.course = course;
       this.student = student;
       this.isPresent = isPresent;
       this.date = date;
       this.comments = comments;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public boolean isIsPresent() {
        return this.isPresent;
    }
    
    public void setIsPresent(boolean isPresent) {
        this.isPresent = isPresent;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


