package attendance.entity;
// Generated May 3, 2016 10:26:54 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private Integer courseid;
     private Teacher teacher;
     private String classtitle;
     private Date starttime;
     private Date endtime;
     private int creditHours;
     private Set attendances = new HashSet(0);

    public Course() {
    }

	
    public Course(Teacher teacher, String classtitle, Date starttime, Date endtime, int creditHours) {
        this.teacher = teacher;
        this.classtitle = classtitle;
        this.starttime = starttime;
        this.endtime = endtime;
        this.creditHours = creditHours;
    }
    public Course(Teacher teacher, String classtitle, Date starttime, Date endtime, int creditHours, Set attendances) {
       this.teacher = teacher;
       this.classtitle = classtitle;
       this.starttime = starttime;
       this.endtime = endtime;
       this.creditHours = creditHours;
       this.attendances = attendances;
    }
   
    public Integer getCourseid() {
        return this.courseid;
    }
    
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
    public String getClasstitle() {
        return this.classtitle;
    }
    
    public void setClasstitle(String classtitle) {
        this.classtitle = classtitle;
    }
    public Date getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }
    public Date getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
    public int getCreditHours() {
        return this.creditHours;
    }
    
    public void setCreditHours(int creditHours) {
        this.creditHours = creditHours;
    }
    public Set getAttendances() {
        return this.attendances;
    }
    
    public void setAttendances(Set attendances) {
        this.attendances = attendances;
    }




}


