package attendance.entity;
// Generated May 3, 2016 10:26:54 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private String rollno;
     private String fullname;
     private String email;
     private Set attendances = new HashSet(0);

    public Student() {
    }

	
    public Student(String rollno, String fullname, String email) {
        this.rollno = rollno;
        this.fullname = fullname;
        this.email = email;
    }
    public Student(String rollno, String fullname, String email, Set attendances) {
       this.rollno = rollno;
       this.fullname = fullname;
       this.email = email;
       this.attendances = attendances;
    }
   
    public String getRollno() {
        return this.rollno;
    }
    
    public void setRollno(String rollno) {
        this.rollno = rollno;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getAttendances() {
        return this.attendances;
    }
    
    public void setAttendances(Set attendances) {
        this.attendances = attendances;
    }




}


