package attendance.entity;
// Generated May 3, 2016 10:26:54 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Teacher generated by hbm2java
 */
public class Teacher  implements java.io.Serializable {


     private Integer teacherid;
     private String fullname;
     private String email;
     private String position;
     private Set courses = new HashSet(0);

    public Teacher() {
    }

	
    public Teacher(String fullname, String email, String position) {
        this.fullname = fullname;
        this.email = email;
        this.position = position;
    }
    public Teacher(String fullname, String email, String position, Set courses) {
       this.fullname = fullname;
       this.email = email;
       this.position = position;
       this.courses = courses;
    }
   
    public Integer getTeacherid() {
        return this.teacherid;
    }
    
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }




}


